### ISSUE TITLE
Change Logo 

### ISSUE THREAD

**Issue by Ishaan-Parsone** [CSI-DMCE-2023/NotesApp-HacktoberFest-2023#1]
The logo on the navigation menu is simply normal text; replace that with a fancy and appropriate logo saying  'My Notes'.

**Comment by swaleha2002** [comment]
Hi @Ishaan-Parsone 

I've reviewed the issue regarding updating the logo.
Could you please assign this issue to me? I'll make the necessary updates promptly.

Thank you!

**Comment by Ishaan-Parsone** [comment]
> Hi @Ishaan-Parsone
> 
> I've reviewed the issue regarding updating the logo. Could you please assign this issue to me? I'll make the necessary updates promptly.
> 
> Thank you!

Go ahead!

**Comment by swaleha2002** [comment]
Thanks you! @Ishaan-Parsone
