### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by JainishaPathak** [CSI-DMCE-2023/NotesApp-HacktoberFest-2023#19]
Ensure that your application is responsive. Use media queries or responsive design frameworks to adapt your layout for different screen sizes.

**Comment by OMPOL1705** [comment]
Looks like a great issue to work on. Please assign it to me.

**Comment by JainishaPathak** [comment]
> Looks like a great issue to work on. Please assign it to me.

Yes i assign you this issue
