### ISSUE TITLE
Hover Effects

### ISSUE THREAD

**Issue by JainishaPathak** [CSI-DMCE-2023/NotesApp-HacktoberFest-2023#21]
Add subtle hover effects to cards for user interactivity

**Comment by raviikushh** [comment]
Assign me I'll make UI cool.

**Comment by raviikushh** [comment]
Ok Thanks I've started working on it , can you please add hacktoberfest tags

**Comment by raviikushh** [comment]
Can I use Tailwind CSS..??

**Comment by raviikushh** [comment]
I made a PR please check it.
