### ISSUE TITLE
Remove seconds from 'Last Updated' time display

### ISSUE THREAD

**Issue by Ishaan-Parsone** [CSI-DMCE-2023/NotesApp-HacktoberFest-2023#5]
We do not need to provide the time with seconds, so remove that and make sure it looks something like 

**Last Updated 11:38 AM**

**Comment by Thilagavathi1** [comment]
@Ishaan-Parsone  i would like to work on this issue.Could you please assign this issue to me

**Comment by swaleha2002** [comment]
could you please assign me this issue?

**Comment by Ishaan-Parsone** [comment]
> @Ishaan-Parsone i would like to work on this issue.Could you please assign this issue to me

Sure

**Comment by Thilagavathi1** [comment]
Hi @Ishaan-Parsone 
i have raised an [PR](https://github.com/CSI-DMCE-2023/NotesApp-HacktoberFest-2023/pull/15)  for this issue.Please review it and let me know the feedback.
