### ISSUE TITLE
Remove Outline from Search bar

### ISSUE THREAD

**Issue by Ishaan-Parsone** [CSI-DMCE-2023/NotesApp-HacktoberFest-2023#6]
Get rid of the outline that displays when we enter a search term in the search bar.

**Comment by killerkc12** [comment]
@Ishaan-Parsone can I take this issue?

**Comment by Ishaan-Parsone** [comment]
> @Ishaan-Parsone can I take this issue?

Yes, go ahead

**Comment by killerkc12** [comment]
@Ishaan-Parsone I've given the PR, please check and review
