### ISSUE TITLE
Convert JS files to JSX files

### ISSUE THREAD

**Issue by Ishaan-Parsone** [CSI-DMCE-2023/NotesApp-HacktoberFest-2023#7]
Where appropriate, convert Javascript (JS) files to Javascript (JSX) files.

**Comment by krishna-nayak** [comment]
@Ishaan-Parsone  can I take this issue?

**Comment by ezhillragesh** [comment]
@Ishaan-Parsone  I have made PR already for issue #13 Please check it out

**Comment by Ishaan-Parsone** [comment]
@krishna-nayak @aryankshl I'm assigning you this issue

**Comment by aryankshl** [comment]
hey @Ishaan-Parsone its done can you please check and accept?
